# Generated by Django 3.0.3 on 2020-03-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_topic_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created'], 'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
    ]
