# Generated by Django 3.0.3 on 2020-03-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_newsarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
